### ISSUE TITLE
许可证问题

### ISSUE THREAD

**Issue by Huier-Huang** [ZsFabTest/Nebula-R#1]
你是不是忘记挂开源许可证了？

**Comment by Huier-Huang** [comment]
按理来说TOR和TOU的许可证是GPLV3协议，你也要用GPLv3协议许可证，可你没用，而且最好是直接在源仓库分叉而不是学TOHTOR直接重新创一个仓库，你这已经属于违规了

**Comment by ZsFabTest** [comment]
谢谢提醒，已经挂好了

**Comment by Huier-Huang** [comment]
> 谢谢提醒，已经挂好了

。。。。。你这，大部分模组都是GPLv3协议许可证，包括我的模组，你用了其他模组代码你也得挂GPLV3这个病毒许可证
